[package]
name = "nink"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core library
relm4 = "0.6.2"
# Optional: reusable components
relm4-components = "0.6.2"
# Optional: icons
relm4-icons = { version = "0.6.0", features = ["plus"] }
