[package]
name = "nink"
version = "0.1.0"
edition = "2021"
authors = ["Simon Grunwald <simongrunwald@hotmail.de>"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version = "0.12", features = ["advanced"]}